spring:
  # rabbitmq消息队列
  rabbitmq:
    host: 192.168.30.172
    port: 5672
    username: admin
    password: qweQWE123$%^
    connection-timeout: 1s
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        multiplier: 1
        max-attempts: 3