person:
  user-name: '张三\n历史'
  boss: true
  birth: 2019/12/9
  age: 21
  interests:
    - 篮球
    - 足球
    - "18"
  animal: [ 阿毛, 阿狗 ]
  score:
    english: 80
    math: 90
  salary:
    - 100
    - 111
  pet:
    name: 无敌的存在
    weight: 11111
  all-pets:
    sick:
      - { name: ppp, weight: 100 }
      - name: qqq
        weight: 200
    health:
      - { name: 阿花, weight: 300 }
      - name: 阿草
        weight: 400


spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    contentnegotiation:
      favor-parameter: true

#server:
#  port: 8888

# 配置mybatis规则
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
